# Basis-Image von Nginx verwenden
FROM nginx

# Mounted lokale HTML-Dateien in den Webserver-Ordner
COPY helloworld.html /usr/share/nginx/html/helloworld.html

# Öffnet Port 80 für eingehende Verbindungen
EXPOSE 80