# Basis-Image für MariaDB  
FROM mariadb:latest  

# Umgebungsvariablen für DB-Zugang setzen  
ENV MYSQL_ROOT_PASSWORD=root  
ENV MYSQL_DATABASE=mydb  

# Port 3306 für externe Zugriffe freigeben  
EXPOSE 3306  
