#cloud-config
# source: https://thenewstack.io/deploy-a-kubernetes-cluster-on-ubuntu-server-with-microk8s/
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, microk8s
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBo+qnNu5xxM9vfz4C04M36FHxHNrEMdm5TkFj1/SfVtqunlUOeMpu7nFCZZKnX8HYwf/MkjcBiTYAgncxku8grwl6XuW/pcvmb6/ghSIaw4xtRRSzit7omqJ5d8kXB3+Nd1aaMHsjfly4nkaqswhySVXQqr8Hw6DbWVw8jLLVKEE+5NZHY33hJkhJwK4blCllsGpmQaKi1qxjsN0hZOWNK01iJAydwD8t2xJ0NOYbq8Qas5IyPnRN7SPxvEhIP6WLQ6Ym6Dmf8FwNW1cHLTKabgjzt5f/HKUkKS89dPd3fn4nnFli1BOMECGUIvVlOw2pQNri7+04OOfn2FGlqr5 teacher
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYus4eptPNkBJgGiXQwDEqhDDMe040u9i2FvYB4WlQ4n8YnAVJ5W/hZq9srjKN31q1/IBvz05Sr1siIHYStP+Qnp87GDVGJN/DlGCCDVgaq0aC82ja2fhZDJDmsqeken8WBhhASUZkWTUldl95CfnbXr5dHytHQXVwlQcfajPg19IcnSDnfdisffssoOCr6jTsQ7qqqnfgYaYwC8VV0sKiwGHqxf+47RoVjScbeYCl1VUPJUzFE//podeGQ9+2XpZa7akza0HvD6htRSHEvMMRTBSCraNZRyNT9g3BhyiKYK+uCjWa4urQERvFZGiiHtXLsIc2m/ml7oH2VqM9m6b3 personal-key

groups:
  - microk8s
system_info:
  default_user:
    groups: [microk8s]
ssh_pwauth: false
disable_root: false
package_update: true
package_upgrade: true
packages:
  - curl
runcmd:
  - sudo snap install microk8s --classic
  - mkdir /home/ubuntu/.kube
